const userActionTypes = {
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    IS_USER_PERSISTED: 'IS_USER_PERSISTED',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    UPDATE_PROJECT_NAME: 'UPDATE_PROJECT_NAME',
    TOGGLE_IS_LOGGED_IN: 'TOGGLE_IS_LOGGED_IN'
};

export default userActionTypes;